import {StyleSheet} from 'react-native';
import {color, font, mobileType, radius, tvType} from '../tokens';

export const styles = StyleSheet.create({
  page: {backgroundColor: color.projector, paddingBottom: 60},
  detailLoading: {
    alignItems: 'center',
    backgroundColor: color.projector,
    flex: 1,
    justifyContent: 'center',
  },
  detailLoadingActions: {marginTop: 24},
  hero: {backgroundColor: color.recess, overflow: 'hidden', width: '100%'},
  heroArtwork: {flex: 1, width: '100%'},
  heroMobile: {height: 540},
  heroTv: {height: 570},
  topActions: {alignItems: 'center', flexDirection: 'row', gap: 8},
  heroCopy: {marginTop: 'auto'},
  heroCopyMobile: {paddingBottom: 42, paddingHorizontal: 20},
  heroCopyTv: {maxWidth: 1002, paddingBottom: 66, paddingRight: 72},
  parentMobile: {
    color: color.screenBlueStrong,
    fontFamily: font.demi,
    fontSize: 14,
    lineHeight: 19,
    marginBottom: 5,
  },
  parentTv: {
    color: color.screenBlueStrong,
    fontFamily: font.demi,
    fontSize: 21,
    lineHeight: 28,
    marginBottom: 8,
  },
  title: {color: color.silver},
  detailTitleMobile: {
    fontFamily: font.bold,
    fontSize: 40,
    letterSpacing: -1.1,
    lineHeight: 44,
  },
  detailTitleTv: {
    fontFamily: font.bold,
    fontSize: 52,
    letterSpacing: -1.5,
    lineHeight: 58,
  },
  metaMobile: {
    color: color.softSilver,
    fontFamily: font.demi,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  metaTv: {
    color: color.softSilver,
    fontFamily: font.demi,
    fontSize: 22,
    lineHeight: 29,
    marginTop: 11,
  },
  summaryMobile: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 15,
    lineHeight: 21,
    marginTop: 10,
  },
  summaryTv: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 23,
    lineHeight: 32,
    marginTop: 13,
    maxWidth: 900,
  },
  resumeProgress: {
    backgroundColor: 'rgba(244,247,250,0.24)',
    height: 4,
    marginTop: 14,
    maxWidth: 520,
  },
  resumeProgressTv: {height: 6, marginTop: 18, maxWidth: 700},
  resumeProgressValue: {
    backgroundColor: color.screenBlueStrong,
    height: '100%',
  },
  actions: {alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 18},
  actionsTv: {gap: 12, marginTop: 24},
  detailBody: {gap: 26, paddingHorizontal: 16, paddingTop: 22},
  detailBodyTv: {gap: 36, paddingLeft: 0, paddingRight: 72, paddingTop: 30},
  liveSection: {gap: 12},
  seasonSelector: {alignItems: 'flex-start', gap: 8},
  seasonTrigger: {
    alignItems: 'center',
    backgroundColor: color.recess,
    borderColor: color.line,
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 44,
    paddingHorizontal: 14,
    width: 220,
  },
  seasonTriggerTv: {minHeight: 58, paddingHorizontal: 18, width: 320},
  seasonControlFocused: {backgroundColor: color.raisedSlate, borderColor: color.focus},
  seasonControlPressed: {backgroundColor: color.brightSlate},
  seasonLabelMobile: {color: color.silver, fontFamily: font.demi, fontSize: 15},
  seasonLabelTv: {color: color.silver, fontFamily: font.demi, fontSize: 22},
  seasonOptions: {
    backgroundColor: color.recess,
    borderColor: color.line,
    borderRadius: 10,
    borderWidth: 1,
    padding: 4,
    width: 220,
  },
  seasonOptionsTv: {padding: 6, width: 320},
  seasonOption: {
    alignItems: 'center',
    borderColor: color.transparent,
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 42,
    paddingHorizontal: 10,
  },
  seasonOptionSelected: {backgroundColor: color.slate},
  seasonOptionMobile: {color: color.softSilver, fontFamily: font.medium, fontSize: 15},
  seasonOptionTv: {color: color.softSilver, fontFamily: font.medium, fontSize: 21},
  episodeLoading: {alignItems: 'center', flexDirection: 'row', gap: 10, minHeight: 90},
  episodeContinuation: {alignItems: 'flex-start', marginTop: -22},
  people: {gap: 14, paddingBottom: 6},
  peopleTv: {gap: 22, paddingBottom: 10},
  person: {
    alignItems: 'center',
    borderColor: color.transparent,
    borderRadius: 10,
    borderWidth: 2,
    padding: 5,
    width: 112,
  },
  personTv: {borderRadius: 14, padding: 7, width: 170},
  personSelected: {
    backgroundColor: color.recess,
    borderColor: color.screenBlueDeep,
  },
  personFocused: {backgroundColor: color.raisedSlate, borderColor: color.focus},
  personPressed: {backgroundColor: color.brightSlate},
  headshot: {
    backgroundColor: color.recess,
    borderRadius: 46,
    height: 92,
    width: 92,
  },
  headshotTv: {borderRadius: 72, height: 144, width: 144},
  headshotFallback: {
    alignItems: 'center',
    borderColor: color.line,
    borderWidth: 1,
    justifyContent: 'center',
  },
  initialsMobile: {
    color: color.softSilver,
    fontFamily: font.demi,
    fontSize: 23,
  },
  initialsTv: {color: color.softSilver, fontFamily: font.demi, fontSize: 34},
  personNameMobile: {
    color: color.silver,
    fontFamily: font.demi,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 7,
    maxWidth: '100%',
  },
  personNameTv: {
    color: color.silver,
    fontFamily: font.demi,
    fontSize: 19,
    lineHeight: 25,
    marginTop: 10,
    maxWidth: '100%',
  },
  personRoleMobile: {
    color: color.dimSilver,
    fontFamily: font.regular,
    fontSize: 11,
    lineHeight: 15,
    maxWidth: '100%',
  },
  personRoleTv: {
    color: color.dimSilver,
    fontFamily: font.regular,
    fontSize: 16,
    lineHeight: 22,
    maxWidth: '100%',
  },
  personLoading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
  },
  personLoadingMobile: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 14,
  },
  personLoadingTv: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 20,
  },
  movieBody: {gap: 12},
  movieBodyTv: {gap: 16},
  bodyHeading: {color: color.silver},
  secondaryHeading: {marginTop: 20},
  factGrid: {gap: 7, paddingHorizontal: 12, paddingVertical: 8},
  factGridTv: {
    gap: 10,
    maxWidth: 980,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  fact: {alignItems: 'flex-start', flexDirection: 'row', paddingVertical: 2},
  factLabelMobile: {
    color: color.dimSilver,
    fontFamily: font.medium,
    fontSize: 12,
    lineHeight: 20,
    width: 92,
  },
  factLabelTv: {
    color: color.dimSilver,
    fontFamily: font.medium,
    fontSize: 17,
    lineHeight: 28,
    width: 150,
  },
  factValueMobile: {
    color: color.silver,
    flex: 1,
    fontFamily: font.regular,
    fontSize: 15,
    lineHeight: 20,
  },
  factValueTv: {
    color: color.silver,
    flex: 1,
    fontFamily: font.regular,
    fontSize: 21,
    lineHeight: 28,
  },
  versions: {
    borderTopColor: color.lineSoft,
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 4,
  },
  versionsTrigger: {
    alignItems: 'center',
    borderColor: color.transparent,
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingHorizontal: 12,
  },
  versionsFocused: {
    backgroundColor: color.raisedSlate,
    borderColor: color.focus,
  },
  versionsPressed: {backgroundColor: color.recess},
  noFactsMobile: {
    color: color.dimSilver,
    fontFamily: font.regular,
    fontSize: 14,
    lineHeight: 20,
    padding: 14,
  },
  noFactsTv: {
    color: color.dimSilver,
    fontFamily: font.regular,
    fontSize: 20,
    lineHeight: 28,
    padding: 20,
  },
  aboutMobile: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 16,
    lineHeight: 24,
  },
  aboutTv: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 23,
    lineHeight: 34,
    maxWidth: 1200,
  },
  seriesBody: {gap: 12},
  episodes: {gap: 8, paddingBottom: 8, paddingTop: 14},
  episodesTv: {gap: 18, paddingBottom: 12, paddingTop: 20},
  episodeWrapper: {paddingBottom: 4},
  player: {flex: 1},
  playerUnavailableScrim: {
    backgroundColor: 'rgba(0,0,0,0.68)',
    ...StyleSheet.absoluteFillObject,
  },
  playerUnavailable: {
    alignItems: 'flex-start',
    alignSelf: 'center',
    backgroundColor: 'rgba(7,11,16,0.88)',
    borderColor: color.line,
    borderRadius: 12,
    borderWidth: 1,
    gap: 14,
    marginTop: 'auto',
    marginBottom: 'auto',
    maxWidth: 420,
    padding: 24,
    width: '86%',
  },
  playerUnavailableTv: {borderRadius: 16, gap: 20, maxWidth: 700, padding: 38},
  playerUnavailableTitleMobile: {
    color: color.silver,
    fontFamily: font.bold,
    fontSize: 24,
    letterSpacing: -0.5,
    lineHeight: 29,
  },
  playerUnavailableTitleTv: {
    color: color.silver,
    fontFamily: font.bold,
    fontSize: 38,
    letterSpacing: -0.8,
    lineHeight: 46,
  },
  playerUnavailableBodyMobile: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 15,
    lineHeight: 22,
  },
  playerUnavailableBodyTv: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 22,
    lineHeight: 32,
  },
  playerScrim: {
    backgroundColor: 'rgba(0,0,0,0.34)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  playerReconnectStatus: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(7,11,16,0.88)',
    borderColor: color.lineStrong,
    borderRadius: radius.surface,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    maxWidth: '92%',
    paddingHorizontal: 18,
    paddingVertical: 14,
    position: 'absolute',
    top: '46%',
    zIndex: 6,
  },
  playerReconnectCopy: {flexShrink: 1},
  playerReconnectTitle: {
    color: color.silver,
    fontFamily: font.bold,
    fontSize: 16,
    lineHeight: 20,
  },
  playerReconnectBody: {
    color: color.softSilver,
    fontFamily: font.regular,
    fontSize: 13,
    lineHeight: 18,
    maxWidth: 360,
  },
  playerTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    zIndex: 4,
  },
  playerTopTv: {paddingHorizontal: 72, paddingTop: 48},
  playerIdentity: {left: 20, maxWidth: '72%', position: 'absolute', zIndex: 3},
  watchGroupBanner: {
    alignItems: 'center',
    backgroundColor: 'rgba(7,11,16,0.82)',
    borderColor: color.lineStrong,
    borderRadius: radius.surface,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    left: 20,
    maxWidth: '78%',
    padding: 10,
    position: 'absolute',
    top: 164,
    zIndex: 4,
  },
  watchGroupBannerTv: {left: 70, maxWidth: 760, padding: 14, top: 178},
  watchGroupCopy: {flex: 1},
  watchGroupTitleMobile: {...mobileType.card, color: color.silver},
  watchGroupTitleTv: {...tvType.card, color: color.silver},
  watchGroupMetaMobile: {...mobileType.caption, color: color.softSilver},
  watchGroupMetaTv: {...tvType.caption, color: color.softSilver},
  playerIdentityTv: {left: 72, maxWidth: 850, top: 58},
  buffering: {alignItems: 'center', flex: 1, justifyContent: 'center'},
  bufferingTextMobile: {
    color: color.silver,
    fontFamily: font.demi,
    fontSize: 17,
  },
  bufferingTextTv: {color: color.silver, fontFamily: font.demi, fontSize: 26},
  playerSpacer: {flex: 1},
  segmentPrompt: {alignItems: 'center', alignSelf: 'flex-end', backgroundColor: color.scrimStrong, borderColor: color.lineStrong, borderRadius: radius.surface, borderWidth: 1, flexDirection: 'row', gap: 6, marginBottom: 10, marginHorizontal: 20, padding: 8},
  segmentPromptTv: {gap: 10, marginBottom: 16, marginHorizontal: 72, padding: 12},
  playerBottom: {
    backgroundColor: 'rgba(7,11,16,0.52)',
    marginTop: 'auto',
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  playerBottomTv: {paddingBottom: 36, paddingHorizontal: 72, paddingTop: 20},
  playerTitleMobile: {
    color: color.silver,
    fontFamily: font.demi,
    fontSize: 18,
    lineHeight: 23,
  },
  playerTitleTv: {
    color: color.silver,
    fontFamily: font.demi,
    fontSize: 28,
    lineHeight: 35,
  },
  playerMetaMobile: {
    color: color.dimSilver,
    fontFamily: font.regular,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  playerMetaTv: {
    color: color.dimSilver,
    fontFamily: font.regular,
    fontSize: 19,
    lineHeight: 26,
    marginTop: 3,
  },
  playerTimes: {flexDirection: 'row', justifyContent: 'space-between'},
  trickplayPreview: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: color.slate,
    borderColor: color.lineStrong,
    borderRadius: radius.surface,
    borderWidth: 1,
    bottom: 118,
    overflow: 'hidden',
    position: 'absolute',
    width: 180,
  },
  trickplayImage: {aspectRatio: 16 / 9, width: '100%'},
  trickplayTime: {
    ...mobileType.caption,
    color: color.silver,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  playerProgressTouch: {paddingBottom: 8, paddingTop: 8},
  playerProgressTouchTv: {paddingBottom: 10, paddingTop: 10},
  playerProgress: {backgroundColor: 'rgba(244,247,250,0.28)', height: 5},
  playerProgressTv: {height: 6},
  playerProgressValue: {
    backgroundColor: color.screenBlueStrong,
    height: '100%',
  },
  playerEnded: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(7,11,16,0.88)',
    borderColor: color.line,
    borderRadius: 12,
    borderWidth: 1,
    gap: 18,
    padding: 24,
    position: 'absolute',
    top: '38%',
    zIndex: 6,
  },
  playerEndedTv: {borderRadius: 16, gap: 24, padding: 36},
  playerEndedTitleMobile: {
    color: color.silver,
    fontFamily: font.bold,
    fontSize: 24,
  },
  playerEndedTitleTv: {
    color: color.silver,
    fontFamily: font.bold,
    fontSize: 38,
  },
  playerEndedMessageMobile: {
    color: color.softSilver,
    fontFamily: font.medium,
    fontSize: 15,
    lineHeight: 21,
    maxWidth: 300,
    textAlign: 'center',
  },
  playerEndedMessageTv: {
    color: color.softSilver,
    fontFamily: font.medium,
    fontSize: 23,
    lineHeight: 31,
    maxWidth: 720,
    textAlign: 'center',
  },
  postPlayActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  playerTimeMobile: {
    color: color.softSilver,
    fontFamily: font.medium,
    fontSize: 12,
  },
  playerTimeTv: {
    color: color.softSilver,
    fontFamily: font.medium,
    fontSize: 18,
  },
  playerFailure: {
    backgroundColor: color.projector,
    flex: 1,
    justifyContent: 'center',
  },
  playerFailureOverlay: {...StyleSheet.absoluteFillObject, zIndex: 8},
  failureActions: {flexDirection: 'row', gap: 8},
  failureActionsTv: {gap: 12},
});
